# Generated by Django 4.0.4 on 2022-05-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(default='Student', max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('contact', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
        ),
    ]
