# Generated by Django 4.0.4 on 2022-05-12 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_dob_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 12, 16, 16, 5, 297539)),
            preserve_default=False,
        ),
    ]
