# Generated by Django 4.0.4 on 2022-05-14 08:52

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(choices=[('OM', 'OM'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC'), ('Other', 'Other')], max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[accounts.models.validate_number]),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street_address', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField(validators=[accounts.models.validate_pincode])),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
